project_id = "wyslzrnmnqzntmuwzkwn"

[functions.export-report-pdf]
verify_jwt = false

[functions.run-scheduled-reports]
verify_jwt = false

[functions.generate-report-data]
verify_jwt = true

[functions.calculate-target-progress]
verify_jwt = true

[functions.calculate-commission-data]
verify_jwt = true

[functions.send-tenant-invitation]
verify_jwt = true

[functions.accept-tenant-invitation]
verify_jwt = false

[functions.onedrive-auth]
verify_jwt = true

[functions.admin-reset-user-password]
verify_jwt = true

[functions.link-invitation-to-account]
verify_jwt = true

[functions.create-account-from-invitation]
verify_jwt = false

[functions.sync-to-google]
verify_jwt = false